import { z } from "zod/v4";
import { listParamsSchema } from "./setup";

export const createItemSchema = z.object({
  barcode: z.string().min(1).max(50),
  name: z.string().min(1).max(1500),
  modelNo: z.string().min(1).max(250),
  unitId: z.number().int().positive(),
  brandId: z.number().int().positive(),
  mainCategoryId: z.number().int().positive(),
  subCategory1Id: z.number().int().positive(),
  subCategory2Id: z.number().int().positive(),
  packingTypeId: z.number().int().positive().nullable().optional(),
  supplierId: z.number().int().positive().nullable().optional(),
  currencyId: z.number().int().positive().nullable().optional(),
  salesRate: z.coerce.number().default(0),
  fobPrice: z.coerce.number().default(0),
  defaultPrice: z.coerce.number().default(0),
  estimatedArrivalPrice: z.coerce.number().default(0),
  shipmentCostPara: z.coerce.number().default(0),
  customsCostPara: z.coerce.number().optional(),
  conversionRate: z.coerce.number().optional(),
  salesMarkup: z.coerce.number().optional(),
  vatPerc: z.coerce.number().optional(),
  maximumQuantity: z.coerce.number().default(0),
  minimumQuantity: z.coerce.number().default(0),
  reOrderQuantity: z.coerce.number().default(0),
  weight: z.coerce.number().default(0),
  actualWeight: z.coerce.number().default(0),
  height: z.coerce.number().default(0),
  depth: z.coerce.number().default(0),
  width: z.coerce.number().optional(),
  volumetricWeight: z.coerce.number().default(0),
  packagingDimension: z.coerce.number().default(0),
  itemType: z.enum(["FREE_TEXT", "ITEM", "COMBO", "OHP", "NON_SERIAL", "COST_ITEM"]).default("ITEM"),
  isActive: z.boolean().default(true),
  isCombo: z.boolean().default(false),
  hasSerialNumber: z.boolean().default(true),
  isServices: z.boolean().default(false),
  isAccessories: z.boolean().default(false),
  isLabor: z.boolean().default(false),
  imagePath: z.string().max(250).nullable().optional(),
  pdfDocPath: z.string().max(250).nullable().optional(),
  footprintPath: z.string().max(250).nullable().optional(),
  estimatedArrivalTime: z.number().int().nullable().optional(),
  manCode1: z.string().max(50).nullable().optional(),
  manCode2: z.string().max(50).nullable().optional(),
});

export const updateItemSchema = createItemSchema.partial();

export const listItemsSchema = listParamsSchema.extend({
  brandId: z.coerce.number().int().positive().optional(),
  mainCategoryId: z.coerce.number().int().positive().optional(),
  subCategory1Id: z.coerce.number().int().positive().optional(),
  subCategory2Id: z.coerce.number().int().positive().optional(),
  itemType: z.enum(["FREE_TEXT", "ITEM", "COMBO", "OHP", "NON_SERIAL", "COST_ITEM"]).optional(),
  isActive: z.coerce.boolean().optional(),
  sortBy: z.string().default("name"),
});
